// <auto-generated />
using AspStore.ShopUI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspStore.ShopUI.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240304201022_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspStore.ShopUI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Phone",
                            Description = "Phone (2a) is coming to the US for developers through our new Developer Program.",
                            Name = "Nothing Phone 2a",
                            Price = 17000000
                        },
                        new
                        {
                            Id = 2,
                            Category = "Phone",
                            Description = "The Google Pixel 8a should arrive in May, if we take the 7a's realease as a guideline, and the number of recent leaks makes it plausible.",
                            Name = "Google Pixel 8a",
                            Price = 20000000
                        },
                        new
                        {
                            Id = 3,
                            Category = "Phone",
                            Description = " iPhone SE 4 would include this 5G chip. A report from MacRumors indicated Apple is indeed developing a new iPhone SE that reportedly includes some dramatic upgrades",
                            Name = "Iphone SE 4",
                            Price = 20000000
                        },
                        new
                        {
                            Id = 4,
                            Category = "Phone",
                            Description = "Cutting corners - it's the story of the LG G6's life. And we mean this both literally and figuratively. Literally because its display doesn't have right angles, it's soft arcs instead.",
                            Name = "LG G6",
                            Price = 7000000
                        },
                        new
                        {
                            Id = 5,
                            Category = "PC",
                            Description = "An OLED screen with larger picture, better battery life, faster WiFi—\r\non top of world class ergonomics and an intuitive console-like experience",
                            Name = "Steam Deck Oled",
                            Price = 40000000
                        },
                        new
                        {
                            Id = 6,
                            Category = "PC",
                            Description = "Experience handheld gaming perfection with console-level performance and graphics, a super vivid touchscreen display, controls that will keep you at the top of the leaderboards & so much more.\r\n\r\n\r\n",
                            Name = "Lenovo Legion GO",
                            Price = 50000000
                        },
                        new
                        {
                            Id = 7,
                            Category = "PC",
                            Description = "MSI Claw A1M, a groundbreaking handheld gaming device that marks a new era in portable gaming experiences. ",
                            Name = "MSI Claw",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 10,
                            Category = "PC",
                            Description = "Sink deep into your favorite AAA or indie games and watch the hours melt away with an expansive Full HD 120Hz display and incredibly comfortable ergonomics.",
                            Name = "Asus ROG Ally",
                            Price = 34000000
                        },
                        new
                        {
                            Id = 8,
                            Category = "Laptop",
                            Description = "    Durable, entry-level 14\" laptop\r\n    Latest processing power\r\n    Professional graphics\r\n    Blazing-fast WiFi\r\n    Time-saving one-touch calling\r\n    All day battery life",
                            Name = "Lenovo Thinkpad L14 Gen1",
                            Price = 16000000
                        },
                        new
                        {
                            Id = 9,
                            Category = "Laptop",
                            Description = "The world’s most popular laptop is better than ever with even more performance, faster Wi-Fi, and support for up to two external displays",
                            Name = "MacBook Air M3 2024",
                            Price = 83000000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
